apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
  namespace: innovatech
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: admin123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-db
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: mysql
        image: mysql:8
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: "innovatech_db"
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: innovatech
spec:
  selector:
    app: db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306