apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-ventas
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-ventas
  template:
    metadata:
      labels:
        app: api-ventas
    spec:
      containers:
      - name: api-ventas
        image: 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-ventas:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://db:3306/innovatech_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_ENDPOINT
          value: "db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "innovatech_db"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: backend-ventas
  namespace: innovatech
spec:
  type: LoadBalancer
  selector:
    app: api-ventas
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-despachos
  namespace: innovatech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-despachos
  template:
    metadata:
      labels:
        app: api-despachos
    spec:
      containers:
      - name: api-despachos
        image: 676308026508.dkr.ecr.us-east-1.amazonaws.com/innovatech-backend-despachos:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "50m"
        env:
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:mysql://db:3306/innovatech_db?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC&createDatabaseIfNotExist=true"
        - name: SPRING_DATASOURCE_USERNAME
          value: "root"
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        - name: DB_ENDPOINT
          value: "db"
        - name: DB_PORT
          value: "3306"
        - name: DB_NAME
          value: "innovatech_db"
        - name: DB_USERNAME
          value: "root"
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_ROOT_PASSWORD
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: backend-despachos
  namespace: innovatech
spec:
  type: LoadBalancer
  selector:
    app: api-despachos
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081